{
  imports = [
    ./theme
    ./luasnip
    ./snacks
    ./editor/lz-n.nix
    ./editor/whichkey.nix
    ./mini
    ./debug/dap.nix
    ./treesitter/treesitter.nix
    ./treesitter/treesitter-textobjects.nix
    ./treesitter/ts-comments.nix
    ./lsp/conform.nix
    ./lsp/fastaction.nix
    ./lsp/lsp.nix
    ./lsp/trouble.nix
    ./lsp/otter.nix
    ./lang/cpp.nix
    ./lang/css.nix
    ./lang/docker.nix
    ./lang/html.nix
    ./lang/json.nix
    ./lang/lua.nix
    ./lang/markdown.nix
    ./lang/nix.nix
    ./lang/python.nix
    ./lang/shell.nix
    ./lang/yaml.nix
    ./completion/blink.nix
    ./completion/friendly-snippets.nix
    ./git/gitsigns.nix
    ./ui
  ];
}
